replicas: 1
port: 3000
resources:
  limits:
    cpu: "1000m"
    memory: "2Gi"
  requests:
    cpu: "600m"
    memory: "1Gi"


service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: ""
  hosts:
    - host: "zayavki.qlab-{{ ENV_NAME }}.ru"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - zayavki.qlab-{{ ENV_NAME }}.ru
      secretName: "zayavki-frontend-secret"
